#####
#
# hadoop.yml
#
#####

---
- name: settings for ambari
  hosts: ambari
  become: yes
  remote_user: "{{ ssh_remote_user }}"
  roles:
    - settings_for_ambari

- name: settings for Linux
  hosts: all
  become: yes
  remote_user: "{{ ssh_remote_user }}"
  roles:
    - settings_for_linux
