#####
#
# settings_for_database/handlers/main.yml
#
#####

---
- name: Create database for ranger
  shell: su - postgres -c "createdb -O ranger ranger"
  ignore_errors: true

- name: Grant all privileges for ranger
  shell: sudo -i -u postgres -c sh -c "psql postgres -c 'grant all privileges on database ranger to ranger'"
  ignore_errors: true
