#####
#
# settings_for_database/tasks/main.yml
#
#####

---
- name: Include vars of all.yml
  include_vars:
    file: all.yml

- name: postgresql service is enabled
  service:
    name: postgresql
    enabled: yes
  ignore_errors: true

- name: Set pg_hba.conf
  copy:
    src: ../files/pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
    mode: '0644'

- name: Change listen_addreseses of postgresql.conf
  replace:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: listen_addresses = 'localhost'
    replace: listen_addresses = '*'

- name: Create ranger in postgres
  shell: su - postgres -c "createuser -a -d -U postgres test"
  ignore_errors: true
  notify:
    - Create database for ranger
    - Grant all privileges for ranger

- name: postgresql service is restarted
  service:
    name: postgresql
    state: restarted
