#####
#
# settings_for_database/tasks/main.yml
#
#####

---
- name: Include vars of all.yml
  include_vars:
    file: all.yml

- name: postgresql service is enabled
  service:
    name: postgresql
    enabled: yes
  ignore_errors: true

- name: Set pg_hba.conf
  copy:
    src: ../files/pg_hba.conf
    dest: /var/lib/pgsql/data/pg_hba.conf
    mode: '0644'

- name: Change listen_addreseses of postgresql.conf
  replace:
    path: /var/lib/pgsql/data/postgresql.conf
    regexp: listen_addresses = 'localhost'
    replace: listen_addresses = '*'

- name: Create db in postgres
  shell: echo "CREATE DATABASE ranger;" | sudo -u $postgres psql -U postgres
  ignore_errors: true

- name: postgresql service is restarted
  service:
    name: postgresql
    state: restarted
