#####
#
# settings_for_ambari/handlers/main.yml
#
#####

---
- name: Run ambari setup
  shell: ambari-server setup --silent

- name: Set jdbc driver
  shell: ambari-server setup --jdbc-db=postgres --jdbc-driver=/usr/share/java/postgresql-jdbc.jar

- name: Set Hadoop Classpath
  shell: export HADOOP_CLASSPATH=${HADOOP_CLASSPATH}:${JAVA_JDBC_LIBS}:/connector jar path

- name: Make sure the ambari-server service is started
  service:
    name: ambari-server
    state: started

- name: Make sure the ambari-server service is enabled
  service:
    name: ambari-server
    enabled: yes
  ignore_errors: true
