#####
#
# settings_for_linux/handlers/main.yml
#
#####

---
- name: System reboot
  shell: sleep 5 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Keep waiting for reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 30
    timeout: 60
